### ISSUE TITLE
[Application] Rapport d'erreur

### ISSUE THREAD

**Issue by tortueuh** [Skyost/Bacomathiques#81]
Encore moi, après avoir fait remarquer une erreur sur le playstore je reviens ! Et je suis satisfait car j'ai trouvé un meilleur moyen de vous contacter, cette fois-ci, dans la section 《Première》, et dans le chapitre Trigonométrie, dans la partie 《Études des fonctions trigonométriques》 il est inscrit : sin(x-pi) = sin(x). Ce qui est faux, sin(x-pi) = -sin(x). Vu que sinus est récurente sur + 2kpi, bref, ça ne change rien au fait que l'app soit super ! Merci pour l'application.

**Comment by Skyost** [comment]
Merci beaucoup ! Je viens de corriger cela, n'hésitez pas si vous voyez d'autres coquilles par-ci par-là 😉

**Comment by Skyost** [comment]
J'en profite pour reprendre le post-scriptum de la réponse que j'ai laissée sur le Play Store : je dois dire que je suis impressionné par le niveau qu'est le vôtre à cette période de votre scolarité… En espérant que vous trouviez dans cette application tout le nécessaire pour en apprendre un peu plus sur les mathématiques des classes supérieures !

**Comment by tortueuh** [comment]
Merci pour ces compliments ! Et effectivement l'application va grandement m'aider !
